Add a POST form to the landing page
prometheus/exporter-toolkit pull request #144
Opened 2023-03-25 11:38 UTC by SuperQ

Add configuration to the landing page generator to allow a POST form.
* Reduce header font size.

2023-03-25 11:39 UTC, SuperQ commented
Screenshot example for the snmp_exporter:

![image](https://user-images.githubusercontent.com/1320667/227715303-919eb9f0-7bcf-4896-bab7-5a04970e16bb.png)

2023-03-29 16:24 UTC, juliusv commented
:+1: Good enough for this purpose :) If you wanted to avoid the input length business, you could also just put the label and input on separate lines (like it's done in most forms nowadays), but this way is also fine.

2023-03-30 05:51 UTC, SuperQ commented
Yea, I was just trying to keep the inline format.

2023-03-30 05:51 UTC, merged

2023-03-30 06:03 UTC, roidelapluie requested changes

2023-03-30 06:03 UTC, roidelapluie commented
My comment was still pending..

2023-03-30 06:26 UTC, SuperQ commented on web/landing_page.html
> +      <label>{{ .Label }}:</label>&nbsp;<input type="{{ .Type }}" name="{{ .Name }}" placeholder=" .Placeholder }}" value="{{ .Value }}"><br>
Oh, oops, will followup.