Further secure TLS communications
prometheus/exporter-toolkit pull request #97
Opened 2022-06-06 16:31 UTC by saroshali-dbx

Closes https://github.com/prometheus/exporter-toolkit/issues/96

2022-07-15 14:30 UTC, saroshali-dbx commented
gentle ping @roidelapluie @SuperQ :) 

For context, here's the issue created for the downstream dependency - https://github.com/weaveworks/common/issues/242

2022-08-01 04:19 UTC, SuperQ commented
I thought most certificate validation has moved to verifying SANs, not CNs.

2022-08-01 12:56 UTC, saroshali-dbx commented
> I thought most certificate validation has moved to verifying SANs, not CNs.

Yeah, thats the intention with SANs to be able to get around the limitation of only being able to specify a single server-name in CN. I ported this functionality from etcd -- and my organization still utilizes common-name -- but I can update this PR to check SANs first and then fallback to CNs. How does that sound?

2022-10-18 10:28 UTC, roidelapluie commented
Actually that's a good point @SuperQ , even go uses SAN's and has removed support for CN. I think we should follow go and use SANs

2022-10-24 08:39 UTC, SuperQ requested changes
Common Name is deprecated for validation. This needs to use SANs.

From [RFC 2818, May 2000](https://www.ietf.org/rfc/rfc2818.html):

>  Although the use of the Common Name is existing practice, it is deprecated and Certification Authorities are encouraged to use the dNSName instead.

Chrome-based browsers dropped CN-only in 2017.

2023-03-17 15:29 UTC, logopk commented
Just a question: is SAN or any other DNS unusual for client certs? I usually create them with 

`C = DE, ST = xxx, L = xx, O = xxx, OU = xxx, CN=me@myself.de`

Thus given the 3.2 
`SHOULD check the identity as described above`

leads me to
`Otherwise, the (most specific) Common Name field in the Subject field of the certificate MUST be used`

2026-08-24 17:23 UTC, ArthurSens commented
Thank you for the work on tightening client-certificate validation and for the thoughtful discussion around Common Names and SANs. The validation direction raised in review was not resolved here, and the TLS implementation has moved on enough that this branch no longer applies cleanly. We are closing it as part of the backlog cleanup, but the use case and discussion remain valuable references. If the need remains, we would welcome a fresh PR based on the current TLS implementation.

2026-08-24 17:23 UTC, closed without merging